import{c as M,a as d,e as o,j as m,h as g,l as S,f as A,v as D}from"../../../_app/immutable/chunks/index-ff400fad.js";import{h,b as z,d as C,e as F}from"../../../_app/immutable/chunks/store-3e4ea696.js";import{i as O}from"../../../_app/immutable/chunks/utils-a62a4de9.js";import{r as B,d as q,p as E,i as R}from"../../../_app/immutable/chunks/system-eda41220.js";import"short-uuid";import"../../../_app/immutable/chunks/finder-762cc408.js";import"buffer";import"lodash";import G from"dragselect";import{P as H}from"../../../_app/immutable/chunks/Previewable-3a8a83f0.js";import"../../../_app/immutable/chunks/index-2945f287.js";const J=M((f,i,r,I)=>{let n,t,c;c=d(h,u=>t=u);let{style:s}=i,{classes:a}=i;return i.style===void 0&&r.style&&s!==void 0&&r.style(s),i.classes===void 0&&r.classes&&a!==void 0&&r.classes(a),n=t[B]?.children.length>0||t[B]?.children.length>0?"url(/images/xp/icons/RecycleBinfull.png)":"url(/images/xp/icons/RecycleBinempty.png)",c(),`<div class="${"flex flex-col items-center absolute bottom-2 right-2 "+o(a,!0)}"${m("style",s,0)}><div class="w-[40px] h-[40px] bg-contain"${g({"background-image":n})}></div>
    <p class="text-center text-[11px] font-MSSS text-white" style="text-shadow: 1px 1px 2px black;">Recycle Bin</p></div>`});let p=80;const ee=M((f,i,r,I)=>{let n,t,c,s,a,u,v,_,$;c=d(h,e=>t=e),a=d(z,e=>s=e),v=d(C,e=>u=e),$=d(F,e=>_=e);let y=q,P=!0,j,{renaming:x=!1}=i;const w=new G({customStyles:!1,draggability:!0});w.subscribe("callback",e=>{for(let l of e.items){let b=l.getAttribute("fs-id");b!=null&&t[b]!=null&&(O(l.style.transform)||S(h,t[b].desktop_css_transform=l.style.transform,t))}S(z,s=e.items.map(l=>l.getAttribute("fs-id")).filter(l=>t[l]!=null),s),console.log(s.map(l=>t[l]))}),new MutationObserver(e=>{w.setSettings({selectables:[]})});function k(e){return e.icon!=null?`url(${e.icon})`:R[e.ext]!=null?`url(/images/xp/icons/${R[e.ext]})`:null}return i.renaming===void 0&&r.renaming&&x!==void 0&&r.renaming(x),n=t[y]==null?[]:t[y].children.map(e=>t[e]).filter(e=>e!=null),c(),a(),v(),$(),`<div class="absolute z-0 inset-0 overflow-hidden bg-transparent"${m("this",j,0)}><div class="${["top-0 left-0 bottom-0 absolute flex flex-col flex-wrap",""].join(" ").trim()}">${A(n,(e,l)=>`<div${m("fs-id",e.id,0)} class="relative fs-item w-[150px] flex-shrink-0 flex-grow-0 overflow-hidden m-2 inline-flex flex-col items-center font-MSSS"${g({transform:e.desktop_css_transform,width:`${p}px`,height:`${p}px`})}>${E.includes(e.ext)?`${D(H,"Previewable").$$render(f,{size:40,default_icon:k(e),fs_id:e.id},{},{})}`:`<div class="${"w-[40px] h-[40px] shrink-0 bg-contain bg-no-repeat bg-center "+o(u.includes(e.id)&&_=="cut"?"opacity-70":"",!0)+" "+o(e.type=="folder"?"bg-[url(/images/xp/icons/FolderClosed.png)]":"bg-[url(/images/xp/icons/Default.png)]",!0)}"${g({"background-image":k(e)})}></div>`}
                <p class="${"px-1 mx-0.5 text-[11px] break-words line-clamp-2 text-ellipsis leading-tight text-center text-white "+o(s?.includes(e.id)&&P?"bg-blue-600 text-slate-50":"",!0)}" style="text-shadow: 1px 1px 2px black;">${o(e.executable?e.basename:e.name)}</p>
                ${s.includes(e.id)&&x?`<textarea autofocus class="absolute max-h-[40px] left-0 top-[40px] right-0 bottom-0 overflow-hidden outline-none border-1 border-slate-900 text-[11px] font-MSSS z-50 resize-none">${o(e.name,!0)}</textarea>`:""}
                
            </div>`)}</div>

    ${D(J,"RecycleBin").$$render(f,{style:"width: "+p+"px;height: "+p+"px;"},{},{})}</div>


`});export{ee as default};
