import{c as q,o as W,e as t,h as g,f as y,j as k,a as _,d as A,v as h}from"../../../_app/immutable/chunks/index-ff400fad.js";import B from"./task_bar.svelte.js";import C from"./work_space.svelte.js";import{c as M,h as z,w as I,q as D}from"../../../_app/immutable/chunks/store-3e4ea696.js";import"lodash";import T from"./screensaver.svelte.js";import"../../../_app/immutable/chunks/index-f4ce6120.js";import{set as S}from"idb-keyval";import H from"./start_menu.svelte.js";import U from"./welcome.svelte.js";import{i as E,a as F}from"../../../_app/immutable/chunks/admin-04ad1b95.js";import"./system_tray.svelte.js";import"./program_tray.svelte.js";import"sortablejs";import"./wallpaper.svelte.js";import"../../../_app/immutable/chunks/system-eda41220.js";import"short-uuid";import"./desktop_folder.svelte.js";import"../../../_app/immutable/chunks/utils-a62a4de9.js";import"../../../_app/immutable/chunks/finder-762cc408.js";import"buffer";import"dragselect";import"../../../_app/immutable/chunks/Previewable-3a8a83f0.js";import"../../../_app/immutable/chunks/index-2945f287.js";import"http";import"https";import"follow-redirects";import"url";import"zlib";import"form-data";const L=q((a,b,x,j)=>{let p=[],u=0,i=0,c=0,$=0,n=!1,v=700,d=700,w=M.subscribe(async l=>{if(l==null){n=!1;return}let{x:m,y:e,originator:r,type:s}=l;if(s==null)return;let o;s=="ProgramTile"?o=(await import("../../../_app/immutable/chunks/CMProgramTile-5fefe8e4.js")).make({type:s,originator:r}):s=="Desktop"?o=(await import("../../../_app/immutable/chunks/CMDesktop-5ccb7764.js")).make({type:s,originator:r}):s=="FSItem"?o=(await import("../../../_app/immutable/chunks/CMFSItem-98d4bd8b.js")).make({type:s,originator:r}):s=="FSVoid"?o=(await import("../../../_app/immutable/chunks/CMFSVoid-ade4a9fe.js")).make({type:s,originator:r}):s=="RecycleBin"?o=(await import("../../../_app/immutable/chunks/RecycleBin-55870b1b.js")).make({type:s,originator:r}):console.log("unknown context menu type"),p=o.menu,u=o.required_width,i=o.required_height,v=document.body.offsetWidth,d=document.body.offsetHeight,$=Math.min(m,v-u),c=Math.min(e,d-i),n=!0});W(()=>{w()});let{hide:f=()=>{n=!1,M.set(null)}}=b;return b.hide===void 0&&x.hide&&f!==void 0&&x.hide(f),`<div class="${"context-menu z-20 pt-0.5 absolute border-2 border-slate-200 bg-slate-50 text-slate-900 w-[180px] text-[11px] "+t(n?"":"hidden",!0)}"${g({top:`${c}px`,left:`${$}px`})}>${y(p.filter(l=>l.length>0),(l,m)=>`<div class="${"w-full border-slate-200 "+t(m==p.length-1?"":"border-b",!0)}">${y(l,e=>`<div class="${"py-1 w-full flex flex-row items-center "+t(e.disabled?"":"hover:bg-blue-600",!0)+" relative group "+t(e.disabled?"pointer-events-none":"",!0)}"><div class="w-[20px] ml-1 shrink-0">${e.icon?`<img${k("src",e.icon,0)} class="${"w-[17px] h-[17px] "+t(e.icon_type=="monotone"?"group-hover:invert":"",!0)+" "+t(e.disabled&&e.icon_type=="monotone"?"contrast-50 invert":"",!0)}" alt=""${g({width:`${e.icon_size}px`,height:`${e.icon_size}px`})}>`:""}</div>
                <div class="${"grow "+t(e.font=="bold"?"font-bold":"",!0)+" "+t(e.disabled?"text-slate-400":"group-hover:text-slate-50",!0)}"><p>${t(e.name)}</p></div>
                <div class="w-[10px]">${e.items!=null?'<svg class="fill-slate-900 group-hover:fill-slate-50 w-[10px] h-[10px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512"><path d="M246.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-128-128c-9.2-9.2-22.9-11.9-34.9-6.9s-19.8 16.6-19.8 29.6l0 256c0 12.9 7.8 24.6 19.8 29.6s25.7 2.2 34.9-6.9l128-128z"></path></svg>':""}</div>
                ${e.items!=null?`
                    <div class="${"absolute "+t($>v-2*u?"-left-full":"left-full",!0)+" py-0.5 hidden group-hover:flex flex-col w-[180px] bg-slate-50 border-slate-200 border-2"}"${g({top:`${c>d-2*i?`-${(e.items.length-2)*100}%`:"0"}  `})}>${y(e.items,r=>`${r?`<div class="${"py-1 w-full flex flex-row items-center "+t(r.disabled?"":"hover:bg-blue-600",!0)+" relative group-sub "+t(r.disabled?"pointer-events-none":"",!0)}"><div class="w-[20px] ml-1 shrink-0 flex items-center justify-center">${r.icon?`<img${k("src",r.icon,0)} width="17px" height="17px">`:`${r.check?'<svg class="fill-slate-800 w-1.5 h-1.5 group-sub-hover:fill-slate-50" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 512c141.4 0 256-114.6 256-256S397.4 0 256 0S0 114.6 0 256S114.6 512 256 512z"></path></svg>':""}`}</div>
                                <div class="${"grow "+t(r.font=="bold"?"font-bold":"",!0)+" "+t(r.disabled?"text-slate-400":"group-sub-hover:text-slate-50",!0)}"><p>${t(r.name)}</p></div>
                                <div class="w-[10px]"></div>
                            </div>`:'<div class="h-0.5 bg-slate-200 mx-1"></div>'}`)}
                    </div>`:""}
            </div>`)}
        </div>`)}</div>`}),be=q((a,b,x,j)=>{let p,u,i,c,$,n;u=_(z,e=>p=e),c=_(E,e=>i=e),n=_(F,e=>$=e);let v=A(),d,w=[z.subscribe(async e=>{clearInterval(d),d=setTimeout(async()=>{console.log("update hardDrive"),await S("hard_drive",p)},1e3)}),I.subscribe(async e=>{e!=null&&await S("wallpaper",e)}),D.subscribe(e=>{if(e!=null&&e!="")switch(e){case"shutdown":v("load_page",{url:"./xp/shutdown.svelte"}),D.set(null);break;case"restart":v("load_page",{url:"./xp/shutdown.svelte"});break}})],f;W(()=>{for(let e of w)e();clearInterval(d)});let l,m;do l=!0,m=`<div id="desktop" class="absolute inset-0 p-0">${i?`<div class="admin-banner absolute top-0 left-0 right-0 z-50 bg-gradient-to-r from-yellow-500 via-yellow-400 to-yellow-500 text-black text-center py-1.5 px-4 shadow-lg flex items-center justify-between"><div class="flex-1"></div>
            <div class="flex items-center gap-2"><svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                <span class="font-bold text-xs">ADMIN MODE</span>
                <span class="text-xs opacity-80">- Logged in as ${t($?.username||"Admin")}</span></div>
            <div class="flex-1 flex justify-end"><button class="text-xs bg-red-600 hover:bg-red-700 text-white px-3 py-0.5 rounded shadow-sm transition-colors">Log Out
                </button></div></div>`:""}
    <div class="${["absolute z-0 left-0 right-0 bottom-[30px]",(i?"":"top-0")+" "+(i?"top-[32px]":"")].join(" ").trim()}">${h(C,"WorkSpace").$$render(a,{},{},{})}</div>

    ${h(B,"TaskBar").$$render(a,{},{},{})}
    ${h(H,"StartMenu").$$render(a,{},{},{})}
    ${h(L,"ContextMenu").$$render(a,{},{},{})}</div>

${h(U,"Welcome").$$render(a,{this:f},{this:e=>{f=e,l=!1}},{})}
${h(T,"Screensaver").$$render(a,{timeout:6e4},{},{})}`;while(!l);return u(),c(),n(),m});export{be as default};
